apiVersion: config.my.domain/v1alpha1
kind: Inventory
metadata:
  labels:
    app.kubernetes.io/name: inventory-controller
    app.kubernetes.io/managed-by: kustomize
  name: inventory-sample
spec:
  annotationKey: owned-by
